variables:
  DOCKER_DRIVER: overlay2
  CCXT: 1.18.928
  PORT: 9308
  DOCKERHUB_REPOSITORY: ixdotai/crypto-exporter

stages:
  - lint
  - build

.tags-template: &tags-definition
  tags:
    - ix-ai

.build-template: &build-definition
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"},\"index.docker.io\":{\"auth\":\"${DOCKERHUB_REGISTRY_AUTH}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile --build-arg PORT=${PORT} --destination ${IMAGE_TAG_GITLAB} --destination ${IMAGE_TAG_GITHUB}

pylint:
  image: python:latest
  stage: lint
  script:
    - curl -o .pylintrc https://tool.ix.ai/.pylintrc
    - pip install pylint pygelf prometheus_client "ccxt<=${CCXT}" requests
    - pylint --rcfile=.pylintrc src/*.py
  <<: *tags-definition

build:test:
  except:
    - master
  before_script:
    - export IMAGE_TAG_GITLAB="${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    - export IMAGE_TAG_GITHUB="index.docker.io/${DOCKERHUB_REPOSITORY}:${CI_COMMIT_REF_NAME}"
  <<: *tags-definition
  <<: *build-definition

build:release:
  only:
    - master
  before_script:
    - export IMAGE_TAG_GITLAB="${CI_REGISTRY_IMAGE}:latest"
    - export IMAGE_TAG_GITHUB="index.docker.io/${DOCKERHUB_REPOSITORY}:latest"
  <<: *tags-definition
  <<: *build-definition
