variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CCXT: 1.18.928

stages:
  - lint
  - build

services:
  - docker:dind

pylint:
  image: python:latest
  stage: lint
  script:
    - curl -o .pylintrc https://tool.ix.ai/.pylintrc
    - pip install prometheus_client ccxt pylint requests
    - pylint --rcfile=.pylintrc src/*.py

build:
  image: docker:latest
  stage: build
  only:
    - /^latest$/
    - tags
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - echo "Building with ccxt<=${CCXT}"
    - docker build -f Dockerfile -t ${IMAGE_TAG} --build-arg CCXT="${CCXT}" .
    - docker push ${IMAGE_TAG}
